### ISSUE TITLE
experiments in post-selection CI problem

### ISSUE THREAD

**Issue by MuzheZeng** [stephenslab/ash-packrat#11]
professor, I investigate this problem and found that it might be problematic to using half-normal method to deal with not-unimodal-at-zero problem since everything we modeled is built upon such assumption. In fact, though we get rid of the curtailed interval phenomenon, most estimation of the alternative effect is shrunk to 0 (with mode at 0). It will be clear if I show you the graph. How can I send you plots easily for discussion?

**Comment by pcarbo** [comment]
Hi Muzhe, you can easily attach files, including images, by clicking the "Attach files by dragging & dropping, selecting them, or pasting from the clipboard" text when you add a Comment (see the bottom of the Comment box). 

The easiest way to save the plots as images in RStudio is to click the "Export" button and save the image as PNG. Hope that works for you.

**Comment by stephens999** [comment]
@MuzheZheng just to emphasise that indeed I do not expect the truncated normal to deal with the non zero mode situation. The main question for you to address is whether it might sometimes have advantages in tail behaviour.

**Comment by MuzheZeng** [comment]
@pcarbo I did not see there is a line below the board ha. I know how to export plots from RStudio. Thank you for your reply!

**Comment by MuzheZeng** [comment]
@stephens999 Sure. I won't add non zero mode function for half-normal method. And my draft is almost done~

**Comment by stephens999** [comment]
Don't you think the mode=estimate option will work with halfnormal?
