### ISSUE TITLE
ash output for PosteriorSD

### ISSUE THREAD

**Issue by NKweiwang** [stephenslab/ash-packrat#3]
Hi Matthew,

Ash gives me all NA as output when I want to find the PosteriorSD.
I use the sample code in the help file of ashr package.

``` r
beta = c(rep(0,100),rnorm(100))
sebetahat = abs(rnorm(200,0,1))
betahat = rnorm(200,beta,sebetahat)
beta.ash = ash(betahat, sebetahat)
beta.ash$PosteriorSD
```

**Comment by stephens999** [comment]
this would be better in ashr :)
Anyway, the reason is that the posterior sd is not yet implemented for mixcompdist="uniform", which is the default.
use mixcompdist="normal"
