### ISSUE TITLE
mixfdr package not available

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/ash-packrat#5]
Is this the `mixfdr` package that is being used by `mixfdr.wrapper.R`?

https://cran.r-project.org/web/packages/mixfdr/index.html

It appears that it is no longer being maintained.

**Comment by stephens999** [comment]
yes, available on archive.
https://cran.r-project.org/src/contrib/Archive/mixfdr/

On Mon, Oct 17, 2016 at 11:20 PM, Peter Carbonetto <notifications@github.com
