### ISSUE TITLE
Missing columns in data frames stored in res.RData

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/ash-packrat#7]
Matthew, I've successfully re-knit most of the `analysis/*.Rmd` files using the latest version of the ashr package. However, I'm running to an issue with a few of the scripts that load results in the `res.RData` files generated by the scripts in the `code` folder. It appears that some columns that should contain results of the simulation experiments are missing, and therefore the scripts report errors when I try to run them. I will need some help in understanding what is going on here so I can resolve this issue; it is likely that there is a bug somewhere in the scripts that generate the results to the `output` folder.

**Comment by stephens999** [comment]
Which scripts do you run into the problems with?

**Comment by pcarbo** [comment]
Most of the scripts that load `res.RData` files:

```
checkIP.Rmd
investigate_hu_badcoverage.Rmd
plot_cdf_eg.Rmd
plot_lfsr.Rmd
summarize_coverage.Rmd
```

I don't think that the bug is found in these scripts; I think that `code/dsc-shrink/run_dsc.R` is not outputting all the results to the `res.RData` file.

**Comment by stephens999** [comment]
i've just pushed a change that should fix some of this... can you try?

**Comment by stephens999** [comment]
oh wait i see another problem

**Comment by stephens999** [comment]
ok try now.. pushed a fix

**Comment by pcarbo** [comment]
Okay, I just merged your changes into my branch, `sync-with-general`. I will give it a try and let you know. (Note that the code takes a couple days to run.)
