### ISSUE TITLE
question about ash code.

### ISSUE THREAD

**Issue by MuzheZeng** [stephenslab/ash-packrat#8]
Professor, I have acquired the res.rdata in the output. Then I found that if I want to add method ash.hn.s etc in the experiment I have to rerun the part that generate res.rdata. Can you suggest a way so that I don't have to rerun everything that take so much time?

**Comment by stephens999** [comment]
you should not have to rerun. 

Have you gone through the dscr simple vignette 
https://github.com/stephens999/dscr
https://github.com/stephens999/dscr/blob/master/vignettes/one_sample_location.rmd
this illustrates how to add a method to a dsc and not rerun it.
(actually you do rerun it, but it checks which methods have been run before
and does not rerun them. THat checking takes a little time but nowhere near as
much time as rerunning.)

Matthew

**Comment by pcarbo** [comment]
Perhaps I should clarify the situation. Muzhe is using the output that I generated (it took about 3 days to run).

Muzhe, Matthew is right---if you replace `ashr/output` with what I gave you, you should be able to add a method without having to regenerate all the output files.

**Comment by MuzheZeng** [comment]
Wow that's real quick reply! Thank you! I'll read that immediately~
