### ISSUE TITLE
issue with rendering of html

### ISSUE THREAD

**Issue by stephens999** [stephenslab/ash-packrat#9]
@pcarbo there seems to be an issue with not everything showing up in the html.

look at this:
https://stephenslab.github.io/ash/analysis/efron.fcr.html

the html doen't seem to include the loading of the packages.
but the rmd file does...
https://github.com/stephenslab/ash/blob/master/analysis/efron.fcr.Rmd

**Comment by pcarbo** [comment]
That is because you set `include=FALSE` for some of the chunks:

```bash
grep include *.Rmd | grep FALSE | head -n 4
IPvsEM.Rmd:```{r chunk_options, include=FALSE}
adaptive_shrinkage.Rmd:```{r chunk_options, include=FALSE}
ash_npmle.Rmd:```{r chunk_options, include=FALSE}
checkIP.Rmd:```{r chunk_options, include=FALSE}
```

This evaluates the chunk, but does not include it in the final rendered HTML.

If you prefer I can remove the `include=FALSE` option for all chunks and re-render the HTML.

**Comment by stephens999** [comment]
i see. 
i think some of those chunks actually just source("chunk_options.R") and it makes sense not to include that. But if the chunks also load a library, probably we should include them.
That is, we should probably have separate chunks - one that has source("chunk_options.R") and include=FALSE, and another chunk that loads the library with include=TRUE

**Comment by pcarbo** [comment]
That seems like a reasonable convention. You did that for some notebooks, but not for all of them. I'll make that change and when I do I'll close this issue.

**Comment by pcarbo** [comment]
I've updated the `analysis/*.Rmd` files and re-rendered the HTML files. 

@stephens999 Please go ahead and close this issue if the new webpages look good to you.
